frontend/modules/project/models/Project.php
<?php

namespace frontend\modules\project\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\BlameableBehavior;
use common\models\User;

/**
 * This is the model class for table "project".
 *
 * @property int $id_project
 * @property string $title
 * @property int $id_client
 * @property int $status
 * @property int $created_by
 * @property int $created_at
 * @property int $updated_at
 *
 * @property ProjectClient $client
 * @property ProjectTask[] $projectTasks
 */
class Project extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $user;
    public static function tableName()
    {
        return 'project';
    }

    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                // 'value' => new \yii\db\Expression('NOW()'),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['id_client', 'status'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['id_client'], 'exist', 'skipOnError' => true, 'targetClass' => ProjectClient::class, 'targetAttribute' => ['id_client' => 'id_client']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_project' => 'ID Projek',
            'title' => 'Nama Projek',
            'id_client' => 'Klien',
            'status' => 'Status',

            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function getUsercreator() //c/u
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    public function getUserupdater() //c/u
    {
        return $this->hasOne(User::class, ['id' => 'updated_by']);
    }

    public function getClient()
    {
        return $this->hasOne(ProjectClient::class, ['id_client' => 'id_client']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasks()
    {
        return $this->hasMany(ProjectTask::class, ['id_project' => 'id_project']);
    }

    public function getTasksunstart()
    {
        return $this->hasMany(ProjectTask::class, ['id_project' => 'id_project'])->onCondition(['status' => 0]);
    }

    public function getTasksfinished()
    {
        return $this->hasMany(ProjectTask::class, ['id_project' => 'id_project'])->onCondition(['status' => 10]);
    }

    public function getTasksprogress()
    {
        return $this->hasMany(ProjectTask::class, ['id_project' => 'id_project'])->onCondition(['status' => 5]);
    }
}

frontend/modules/project/controllers/ProjectController.php
<?php

namespace frontend\modules\project\controllers;

use Yii;
use frontend\modules\project\models\Project;
use frontend\modules\project\models\ProjectTask;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * ProjectController implements the CRUD actions for Project model.
 */
class ProjectController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                // 'only' => ['logout', 'signup'],
                'rules' => [
                    /*[
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],*/
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Project models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = Project::find();

        return $this->renderAjax('index', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Project model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ProjectTask::find()->orderBy(['created_at' => SORT_DESC])->where(['id_project' => $id]),
        ]);

        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id = null)
    {
        $model = new Project();

        if ($id != null) {
            $model->id_client = $id;
        }

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                $data = ['status' => 1, 'message' => 'berhasil menambah data projek',  'data' => $model];
            } else {
                $data = ['status' => 0, 'message' => 'terjadi kesalahan saat menambah data projek', 'data' => $model->getErrors()];
            }

            return $this->asJson($data);
        } else {

            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                $data = ['status' => 1, 'message' => 'berhasil menambah data projek',  'data' => $model];
            } else {
                $data = ['status' => 0, 'message' => 'terjadi kesalahan saat menambah data projek', 'data' => $model->getErrors()];
            }

            return $this->asJson($data);
        } else {

            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Project model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if ($model->delete()) {
            $data = ['status' => 1, 'message' => 'Berhasil menghapus data projek',  'data' => $model];
        } else {
            $data = ['status' => 0, 'message' => 'terjadi kesalahan saat menghapus data projek', 'data' => $model->getErrors()];
        }

        return $this->asJson($data);
    }

    /**
     * Finds the Project model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Project the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Project::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/modules/project/views/project/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use frontend\modules\project\models\ProjectClient;
/* @var $this yii\web\View */
/* @var $model frontend\modules\project\models\Project */
/* @var $form yii\widgets\ActiveForm */

$arr = ArrayHelper::map(ProjectClient::find()->all(), 'id_client', 'client_name');

$arrFormConfig = [
    'id' => $model->formName()
];

$backUrl = 'goLoad({url:\'/project/project-client/view?id=' . $model->id_client . '\'});';
?>

<div class="project-form">
    <div class="panel panel-default">
        <div class="panel-body">
            <?php $form = ActiveForm::begin($arrFormConfig); ?>

            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'id_client')->dropdownList($arr) ?>

            <?= $form->field($model, 'status')->dropdownList([0 => 'Non-Aktif', 10 => 'Aktif']) ?>

            <div class="form-group">
                <?= Html::submitButton('Simpan', ['id' => 'btn-submit-client', 'class' => 'btn btn-success']) ?>
                <a href="javascript:void(0)" onclick="<?= $backUrl ?>" class="btn btn-primary"> Kembali </a>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<?php
$script = <<<JS
//regularly-ajax
sendForm({formName: 'form#{$model->formName()}', module:'project > project > form',disabledButton:'#btn-submit-client', successTask:function(res){
  console.log(res);
  responseModal({
    title:'Berhasil',
    type:'success',
    target:'body',
    text:res.message,
    timer:3000,
    onAfterClose:function(){
        {$backUrl}
    }
  });

}});
JS;

$this->registerJs($script);

frontend/modules/project/views/project/bak.view.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $model frontend\modules\project\models\Project */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<style type="text/css">
    .breakword {
        display: inline-block;
        width: 700px;
        word-wrap: break-word;
        white-space: pre-wrap;
        hyphens: auto;
    }
</style>
<div class="project-view">
    <div class="panel panel-default">
        <div class="panel-body">
            <h1><?= Html::encode($this->title) ?></h1>

            <table class="table table-striped table-bordered detail-view">
                <tr>
                    <th width="200">ID Projek</th>
                    <td><?= $model->id_project ?></td>
                </tr>

                <tr>
                    <th>Nama Projek</th>
                    <td><?= $model->title ?></td>
                </tr>

                <tr>
                    <th>Klien</th>
                    <td><?= $model->client->client_name ?></td>
                </tr>

                <tr>
                    <th>Status</th>
                    <td><?= $model->status ?></td>
                </tr>

                <tr>
                    <th>Pembuat</th>
                    <td><?= $model->usercreator->username ?></td>
                </tr>

                <tr>
                    <th>Dibuat pada tanggal</th>
                    <td><?= date('d-F-Y H:i', $model->created_at) ?></td>
                </tr>
            </table>

            <a href="javascript:void(0)" onclick="goLoad({url:'/project/project-task/create?id=<?= $model->id_project ?>'})" class="btn btn-primary btn-sm"> Tambahkan Task </a>

            <div class="table-responsive">
                <?php Pjax::begin() ?>

                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],

                        // 'id',
                        // 'id_project',
                        'ord_id',
                        // 'description:ntext'
                        [
                            'attribute' => 'title',
                            'label' => 'Task',
                            'options' => ['class' => 'breakword'],
                            // 'contentOptions' =>function ($model, $key, $index, $column){
                            //     return ['class' => 'tbl_column_name'];
                            // },
                            'content' => function ($m) {
                                return '<p class="breakword"><b>' . $m->title . '</b><br>' . html_entity_decode($m->description) . '<br><span class="label label-info"><i class="fa fa-user"></i> ' . $m->usercreator->username . '</span><input class="form-control" onClick="this.select();" type="text" value="' . $m->title . '#' . $m->ord_id . '"></p>';
                            }
                        ],
                        [
                            'attribute' => 'status',
                            'label' => 'Status',
                            // 'contentOptions' =>function ($model, $key, $index, $column){
                            //     return ['class' => 'tbl_column_name'];
                            // },
                            'content' => function ($m) {
                                return $m->humanStatus();
                            }
                        ],
                        [
                            'attribute' => 'created_at',
                            'label' => 'Tanggal Masuk',
                            // 'contentOptions' =>function ($model, $key, $index, $column){
                            //     return ['class' => 'tbl_column_name'];
                            // },
                            'content' => function ($m) {
                                return '<span data-livestamp="' . $m->created_at . '"></span>';
                            }
                        ],
                        [
                            'attribute' => 'updated_at',
                            'label' => 'Tanggal Update',
                            // 'contentOptions' =>function ($model, $key, $index, $column){
                            //     return ['class' => 'tbl_column_name'];
                            // },
                            'content' => function ($m) {
                                // return date('d-F-Y H:i', $m->updated_at);
                                return '<span data-livestamp="' . $m->updated_at . '"></span>';
                            }
                        ],
                        //'created_by',
                        //'created_at',
                        //'updated_at',

                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '{popup} {view}<br>{update} {delete}',
                            'urlCreator' => function ($action, $model, $key, $index) {
                                $url_base = Url::base();
                                if ($action === 'view') {
                                    $url = $url_base . '/project/project-task/view?id=' . $model->id;
                                    return $url;
                                }

                                if ($action === 'update') {
                                    $url = $url_base . '/project/project-task/update?id=' . $model->id . '&id_project=' . $model->id_project;
                                    return $url;
                                }
                                if ($action === 'delete') {
                                    $url = $url_base . '/project/project-task/delete?id=' . $model->id . '&id_project=' . $model->id_project;
                                    return $url;
                                }
                            },
                            'buttons' => [
                                'edit' => function ($url, $model) {
                                    return Html::a(
                                        '<span class="glyphicon glyphicon-new-window"></span> ',
                                        $url,
                                        [
                                            'title' => 'Edit ',
                                            'data-pjax' => '0',
                                        ]
                                    );
                                },
                                'popup' => function ($url, $model) {
                                    $urledited = html_entity_decode("url:'" . substr($url, strrpos($url, '?')) . "'");
                                    return Html::a(
                                        '<span class="glyphicon glyphicon-new-window"></span> ',
                                        'javascript:void(0)',
                                        [
                                            'onclick' => "goPopup({" . $urledited . "})",
                                            'title' => 'Buka popup Edit ',
                                            'data-pjax' => '0',
                                        ]
                                    );
                                }
                            ],
                        ],
                    ],
                ]); ?>

                <?php Pjax::end(); ?>
            </div>
        </div>
    </div>
</div>

frontend/modules/project/views/project/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\modules\project\models\Project */

$this->title = 'Buat Projek Baru';
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="project-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/modules/project/views/project/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Projek';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="project-index">
    <div class="panel panel-default">
        <div class="panel-body">
            <h1><?= Html::encode($this->title) ?></h1>

            <p>
                <a href="javascript:void(0)" onclick="goLoad({url:'/project/project/create'})" class="btn btn-primary btn-sm"> Tambahkan Projek </a>
            </p>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th rowspan="2">ID</th>
                        <th rowspan="2">Nama</th>
                        <th rowspan="2">Klien</th>
                        <th colspan="4">Jumlah Tugas</th>
                        <th rowspan="2">Status</th>
                        <th rowspan="2">Aksi</th>
                    </tr>

                    <tr>
                        <th>Unstart</th>
                        <th>Progress</th>
                        <th>Finish</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <?php foreach ($model->all() as $v) : ?>
                    <tr>
                        <td><?= $v->id_project ?></td>
                        <td><?= $v->title ?></td>
                        <td><?= $v->client->client_name ?></td>
                        <td><?= count($v->tasksunstart) ?></td>
                        <td><?= count($v->tasksprogress) ?></td>
                        <td><?= count($v->tasksfinished) ?></td>
                        <td><?= count($v->tasks) ?></td>
                        <td><?= $v->status ?></td>
                        <td>
                            <a href="javascript:void(0)" onclick="goLoad({url:'/project/project/view?id=<?= $v->id_project ?>'})" class="btn btn-sm btn-success"> lihat </a>
                            <a href="javascript:void(0)" onclick="goLoad({url:'/project/project/update?id=<?= $v->id_project ?>'})" class="btn btn-sm btn-warning"> ubah </a>
                            <a href="javascript:void(0)" onclick="goLoad({url:'url'})" class="btn btn-sm btn-danger"> hapus </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>

frontend/modules/project/views/project/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\modules\project\models\Project */

$this->title = 'Update Projek : ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id_project]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="project-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/modules/project/views/project/view.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $model frontend\modules\project\models\Project */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<style type="text/css">
    .breakword {
        display: inline-block;
        width: 700px;
        word-wrap: break-word;
        white-space: pre-wrap;
        hyphens: auto;
    }
</style>
<div class="project-view">
    <div class="panel panel-default">
        <div class="panel-body">
            <h1><?= Html::encode($this->title) ?></h1>

            <table class="table table-striped table-bordered detail-view">
                <tr>
                    <th width="200">ID Projek</th>
                    <td><?= $model->id_project ?></td>
                </tr>

                <tr>
                    <th>Nama Projek</th>
                    <td><?= $model->title ?></td>
                </tr>

                <tr>
                    <th>Klien</th>
                    <td><?= $model->client->client_name ?></td>
                </tr>

                <tr>
                    <th>Status</th>
                    <td><?= $model->status ?></td>
                </tr>

                <tr>
                    <th>Pembuat</th>
                    <td><?= $model->usercreator->username ?></td>
                </tr>

                <tr>
                    <th>Dibuat pada tanggal</th>
                    <td><?= date('d-F-Y H:i', $model->created_at) ?></td>
                </tr>
            </table>



            <div class="table-responsive">
                <div id="task-panel-area"></div>
            </div>
        </div>
    </div>
</div>
<?php
$script = <<<JS
//regularly-ajax
goLoad({elm:'#task-panel-area', url:'/project/project-task/list?id={$model->id_project}'})
JS;

$this->registerJs($script);